// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9pyFpZtb-Meus4QE_xWf6cMFRHu4FuVo',
    appId: '1:797525794992:web:d53521280ebabc30fcdb75',
    messagingSenderId: '797525794992',
    projectId: 'studentswap-fbf76',
    authDomain: 'studentswap-fbf76.firebaseapp.com',
    storageBucket: 'studentswap-fbf76.appspot.com',
    measurementId: 'G-LGCBJBMGET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKlYnHAE3ULmqsN6HokZDqb9vVc853X5Q',
    appId: '1:797525794992:android:9772e6de89c6802bfcdb75',
    messagingSenderId: '797525794992',
    projectId: 'studentswap-fbf76',
    storageBucket: 'studentswap-fbf76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGI8K4iOxZns3yrn4PuaJ09TP2vI6vyEc',
    appId: '1:797525794992:ios:f48dc75bf7b9cd34fcdb75',
    messagingSenderId: '797525794992',
    projectId: 'studentswap-fbf76',
    storageBucket: 'studentswap-fbf76.appspot.com',
    iosClientId: '797525794992-hslfhc3k6q7qe6b4ofrc5isnfva3pqd4.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentswap',
  );
}
